# Generated by Django 2.2.6 on 2023-01-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCov',
            fields=[
                ('conNum', models.IntegerField(default=0, verbose_name='conNum')),
                ('conadd', models.IntegerField(default=0, verbose_name='conadd')),
                ('cureNum', models.IntegerField(default=0, verbose_name='cureNum')),
                ('deathNum', models.IntegerField(default=0, verbose_name='deathNum')),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='name')),
            ],
            options={
                'verbose_name': 'CountryCov',
                'verbose_name_plural': 'CountryCov',
            },
        ),
        migrations.RemoveField(
            model_name='chinacov',
            name='id',
        ),
        migrations.RemoveField(
            model_name='worldcov',
            name='id',
        ),
        migrations.AlterField(
            model_name='chinacov',
            name='ymd',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ymd'),
        ),
        migrations.AlterField(
            model_name='worldcov',
            name='date',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ymd'),
        ),
    ]
