# Generated by Django 2.2.6 on 2023-01-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20230120_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceCov',
            fields=[
                ('cureNum', models.IntegerField(default=0, verbose_name='conNum')),
                ('deathNum', models.IntegerField(default=0, verbose_name='deathNum')),
                ('econNum', models.IntegerField(default=0, verbose_name='econNum')),
                ('jwsrNum', models.IntegerField(default=0, verbose_name='jwsrNum')),
                ('value', models.IntegerField(default=0, verbose_name='value')),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='name')),
            ],
            options={
                'verbose_name': 'ProvinceCov',
                'verbose_name_plural': 'ProvinceCov',
            },
        ),
    ]
