# Generated by Django 4.1.5 on 2023-01-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_provincecov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincecov',
            name='cureNum',
            field=models.IntegerField(default=0, verbose_name='cureNum'),
        ),
    ]
